
from global_settings import OWN_EMAIL, OWN_EMAIL_PASSWORD, SMTP_SSL, SMTP_PORT


OWN_EMAIL = OWN_EMAIL
OWN_EMAIL_PASSWORD = OWN_EMAIL_PASSWORD

SMTP_SSL_ADRESS = SMTP_SSL
SMTP_PORT = SMTP_PORT

    
