"""add_test

Revision ID: 26c8a08cd152
Revises: f3bdb75b400f
Create Date: 2024-03-21 22:04:45.391278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c8a08cd152'
down_revision: Union[str, None] = 'f3bdb75b400f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kv_tasks', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kv_tasks', 'name')
    # ### end Alembic commands ###
