"""delete_taskname

Revision ID: 905c097fb6c3
Revises: 025e9def57b6
Create Date: 2024-03-20 19:14:40.062798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905c097fb6c3'
down_revision: Union[str, None] = '025e9def57b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kv_tasks', 'task_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kv_tasks', sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
