"""add_keys_email

Revision ID: efdef00f4e9b
Revises: 49c41c67fa42
Create Date: 2024-03-21 17:00:25.302900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdef00f4e9b'
down_revision: Union[str, None] = '49c41c67fa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kv_keys', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('kv_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('kv_users', 'is_authenticated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kv_users', 'is_authenticated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('kv_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('kv_keys', 'email')
    # ### end Alembic commands ###
